services:
  groups.repository.group:
    class: Backend\Modules\Groups\Domain\Group\GroupRepository
    factory: ["@doctrine.orm.entity_manager", getRepository]
    arguments:
      - Backend\Modules\Groups\Domain\Group\Group
  groups.repository.setting:
    class: Backend\Modules\Groups\Domain\Setting\SettingRepository
    factory: ["@doctrine.orm.entity_manager", getRepository]
    arguments:
      - Backend\Modules\Groups\Domain\Setting\Setting
